name: Build APPX

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Package App
      run: |
        & "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\makeappx.exe" pack /d . /p MetroChrome_Cloud.appx /o

    - name: Upload Appx Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MetroChrome-Appx-Package
        path: MetroChrome_Cloud.appx
