name: Build Native UWP APPX

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build and Package Project for ARM
      run: |
        msbuild MetroChrome/MetroChrome/MetroChrome.csproj `
          /p:Configuration=Release `
          /p:Platform=ARM `
          /p:AppxBundle=Always `
          /p:AppxBundlePlatforms="ARM" `
          /p:BuildAppxUploadPackageForStore=false `
          /p:UapAppxPackageBuildMode=SideloadOnly

    - name: Upload Finished APPX Bundle
      uses: actions/upload-artifact@v4
      with:
        name: MetroChrome-Native-ARM-Package
        path: MetroChrome/MetroChrome/AppPackages/
